#
# Autor: Davi Garcia <dvercill@redhat.com>
# Data: 14-07-2020
#
# Playbook para configurar e implantar o serviço de backend
#

- name: Deploy application backend service
  hosts: backend
  become: yes
  roles:
  - backend
