#
# Autor: Davi Garcia <dvercill@redhat.com>
# Data: 23-07-2020
#
# Playbook para configurar e implantar o serviço de frontend
#

- name: Deploy application frontend service
  hosts: frontend
  become: yes
  gather_facts: no
  roles:
  - frontend
