#
# Autor: Davi Garcia <dvercill@redhat.com>
# Data: 24-07-2020
#
# Playbook de validação dos componentes de backend/frontend
#

- name: Verify if frontend is functional
  hosts: frontend
  gather_facts: no
  vars:
    frontend_bind_port: 80
  tasks:
  - name: Executing HTTP request (3 retries)
    uri:
      url: "http://{{ ansible_host }}:{{ frontend_bind_port }}"
      return_content: yes
    register: response
    failed_when: "'<h1>Youtube Chapter Extractor</h1>' not in response.content"
    retries: 3
    delay: 3

- name: Verify if backend is functional
  hosts: backend
  vars:
    backend_bind_port: 8080
  gather_facts: no
  tasks:
  - name: Executing HTTP request (3 retries)
    uri:
      url: "http://{{ ansible_host }}:{{ backend_bind_port }}/api/v1/video-chapters/notreal"
    retries: 3
    delay: 3
