#
# Autor: Davi Garcia <dvercill@redhat.com>
# Data: 09-07-2020
#
# Esse arquivo lista as dependências (Role/Collections) dos playbooks.
#

[defaults]

# Configurações que melhoram a experiência no terminal.
stdout_callback = yaml
bin_ansible_callbacks = True

# Configuração para hospedar os Collections juntos do projeto.
collections_paths = ./collections