name: Continous Deployment (CD)

on:
  push:
    branches:
    - master

jobs:
   ansible:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Run Ansible playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        directory: ./
        playbook: main.yml
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: ${{secrets.INVENTORY}}
