name: Continous Integration (CI)

on:
  push:
    branches-ignore:
    - master

jobs:
  application:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: (API) Setup Deno environment
      uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x

    - name: (API) Lint Deno code conventions
      run: deno fmt --check
      working-directory: app-src/youtube-chapter-extractor/api

    - name: (API) Execute Deno tests
      run: deno test --allow-all
      working-directory: app-src/youtube-chapter-extractor/api

  infraestructure:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Lint Ansible code
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          infra-src/main.yml
        override-deps: |
          ansible==2.9
          ansible-lint==4.2
        args: "-c infra-src/.ansible-lint"
