name: Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  application:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Deno environment
      uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x

    - name: Execute Deno Tests
      run: deno test --allow-all
      working-directory: app-src/youtube-chapter-extractor/api

  infraestructure:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Lint Ansible (infra code)
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          infra-src/main.yml
        override-deps: |
          ansible==2.9
          ansible-lint==4.2
